# Generated by Django 4.2.5 on 2023-10-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_teacher_review_count_alter_review_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutephoto',
            name='institute',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='wiki.institute'),
        ),
    ]
