# Generated by Django 4.2.5 on 2023-10-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_institutephoto_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutephoto',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='wiki.institute'),
            preserve_default=False,
        ),
    ]
