# Generated by Django 4.2.5 on 2023-10-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_alter_discipline_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='discipline_photo'),
        ),
    ]
