# Generated by Django 4.2.5 on 2023-10-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_alter_discipline_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplines', to='wiki.teacher'),
        ),
    ]
