# Generated by Django 4.2.5 on 2023-10-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_alter_discipline_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avg_rating',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
    ]
