# Generated by Django 4.2.5 on 2023-10-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0017_teacher_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='student',
            new_name='created_by',
        ),
    ]
