# Generated by Django 4.2.5 on 2023-10-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_rename_student_review_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_by',
            new_name='student',
        ),
    ]
